"""Initial migration

Revision ID: 365be9d4ac7c
Revises: 
Create Date: 2026-03-14 13:33:38.786220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365be9d4ac7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('idx_assets_campaign_id'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_campaign_id'), 'assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.drop_index(op.f('idx_brands_user_id'), table_name='brands')
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.drop_index(op.f('idx_campaigns_brand_id'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_status'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.drop_index(op.f('idx_content_items_schedule_id'), table_name='content_items')
    op.drop_index(op.f('idx_content_items_scheduled_date'), table_name='content_items')
    op.drop_index(op.f('idx_content_items_status'), table_name='content_items')
    op.create_index(op.f('ix_content_items_id'), 'content_items', ['id'], unique=False)
    op.create_index(op.f('ix_content_items_schedule_id'), 'content_items', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_content_items_scheduled_date'), 'content_items', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.drop_index(op.f('idx_schedules_strategy_id'), table_name='content_schedules')
    op.create_index(op.f('ix_content_schedules_id'), 'content_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_content_schedules_strategy_id'), 'content_schedules', ['strategy_id'], unique=False)
    op.drop_index(op.f('idx_strategies_brand_id'), table_name='marketing_strategies')
    op.create_index(op.f('ix_marketing_strategies_brand_id'), 'marketing_strategies', ['brand_id'], unique=False)
    op.create_index(op.f('ix_marketing_strategies_id'), 'marketing_strategies', ['id'], unique=False)
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_metrics_content_id'), table_name='performance_metrics')
    op.drop_index(op.f('idx_metrics_recorded_at'), table_name='performance_metrics')
    op.create_index(op.f('ix_performance_metrics_content_id'), 'performance_metrics', ['content_id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_id'), 'performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_recorded_at'), 'performance_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.drop_index(op.f('idx_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('idx_team_members_user_id'), table_name='team_members')
    op.drop_constraint(op.f('team_members_team_id_user_id_key'), 'team_members', type_='unique')
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_unique_constraint('uq_team_user', 'team_members', ['team_id', 'user_id'])
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_constraint('uq_team_user', 'team_members', type_='unique')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.create_unique_constraint(op.f('team_members_team_id_user_id_key'), 'team_members', ['team_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_index(op.f('idx_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_performance_metrics_recorded_at'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_id'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_content_id'), table_name='performance_metrics')
    op.create_index(op.f('idx_metrics_recorded_at'), 'performance_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('idx_metrics_content_id'), 'performance_metrics', ['content_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.drop_index(op.f('ix_marketing_strategies_id'), table_name='marketing_strategies')
    op.drop_index(op.f('ix_marketing_strategies_brand_id'), table_name='marketing_strategies')
    op.create_index(op.f('idx_strategies_brand_id'), 'marketing_strategies', ['brand_id'], unique=False)
    op.drop_index(op.f('ix_content_schedules_strategy_id'), table_name='content_schedules')
    op.drop_index(op.f('ix_content_schedules_id'), table_name='content_schedules')
    op.create_index(op.f('idx_schedules_strategy_id'), 'content_schedules', ['strategy_id'], unique=False)
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_scheduled_date'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_schedule_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_id'), table_name='content_items')
    op.create_index(op.f('idx_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('idx_content_items_scheduled_date'), 'content_items', ['scheduled_date'], unique=False)
    op.create_index(op.f('idx_content_items_schedule_id'), 'content_items', ['schedule_id'], unique=False)
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.create_index(op.f('idx_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('idx_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.create_index(op.f('idx_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_campaign_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.create_index(op.f('idx_assets_campaign_id'), 'assets', ['campaign_id'], unique=False)
    op.create_index(op.f('idx_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    # ### end Alembic commands ###
