"""add password reset otp fields

Revision ID: 3eb55cee2903
Revises: a1b2c3d4e5f6
Create Date: 2026-05-22 03:43:37.934279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb55cee2903'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_otp_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_otp_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_verified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_verified')
    op.drop_column('users', 'password_reset_otp_expiry')
    op.drop_column('users', 'password_reset_otp_hash')
    # ### end Alembic commands ###
